---
- name: master playbook
  user: ansible
  become: yes
  gather_facts: yes
  hosts:
    - dev
  vars_files:
    -  "{{inventory_dir}}/vars_secure_params.yml"
    -  "{{inventory_dir}}/all.yml"
  roles:
    - common
    # - fw_iptables
    # - dns_bind
    # - web_apache
    # - web_nginx
    # - app_phpfpm
    # - db_mysql
