---
- name: enable services
  service: name={{item}} state=started enabled=yes
  with_items: "{{common_enable_services}}"

- name: disable services
  service: name={{item}} state=stopped enabled=no
  ignore_errors: true
  with_items: "{{common_disable_services}}"
