---
- name: backup initial config files (.orig)
  copy:
    src: "{{ item }}"
    dest: "{{ item }}.orig"
    owner: root
    group: root
    mode: '0400'
    remote_src: yes
    force: no
    backup: no
  with_items:
    - /etc/profile

- name: set login prompt setting
  blockinfile:
    backup: yes
    dest: /etc/profile
    insertafter: EOF
    block: |
      HOSTTYPE: "{{ lookup('env', 'STAGE') }}" # dev or stg or prd
      case "$HOSTTYPE" in
        "dev") PROMPT_COLOR_NUM=32 ;;
        "stg") PROMPT_COLOR_NUM=33 ;;
        "prd") PROMPT_COLOR_NUM=31 ;;
        *)     PROMPT_COLOR_NUM=35 HOSTTYPE="unknown";;
      esac
      export PS1='\[\033[1;${PROMPT_COLOR_NUM}m\][\u@(${HOSTTYPE})\h \W]$\[\033[00m\] '
      export HISTTIMEFORMAT='%F %T '
      export HISTSIZE=100000
