---
- name: backup initial config files (.orig)
  copy:
    src: "{{ item }}"
    dest: "{{ item }}.orig"
    owner: root
    group: root
    mode: '0400'
    remote_src: yes
    force: no
    backup: no
  with_items:
    - /etc/resolv.conf

- name: set hosts - add nameserver entry
  lineinfile:
    dest: /etc/resolv.conf
    state: present
    regexp: '^#? ?nameserver *{{item.name}}'
    line: 'nameserver {{item.name}}'
  with_items:
    - "{{common_name_server}}"
