---
- name: set root password
  no_log: true
  user:
    name: root
    password: "{{ common_user.root.password | password_hash('sha512') }}"

- name: set admin-user(wheel)
  no_log: true
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default('wheel') }}"
    password: "{{ item.password | password_hash('sha512') }}"
  with_items: "{{ common_user.admin }}"
