---
- name: service stop & disabled
  ignore_errors: true
  service:
    name: "{{item.name}}"
    state: stopped
    enabled: no
  with_items:
    - "{{common_disable_services}}"

- name: service start & enabled
  ignore_errors: true
  service:
    name: "{{item.name}}"
    state: started
    enabled: yes
  with_items:
    - "{{common_enable_services}}"
