---
- name: install group packages
  ignore_errors: true
  yum: >
    name="@{{item.name}}"
    state=installed
  with_items:
    - "{{common_group_packages}}"

- name: install packages
  ignore_errors: true
  yum: >
    name="{{item.name}}"
    state=installed
  with_items:
    - "{{common_packages}}"
