- name: set login prompt setting
  blockinfile:
    backup: yes
    dest: /etc/profile
    insertafter: EOF
    block: |
      HOSTTYPE="{{stage}}" # dev or stg or prd
      case "$HOSTTYPE" in
        "dev") PROMPT_COLOR_NUM=32 ;;
        "stg") PROMPT_COLOR_NUM=33 ;;
        "prd") PROMPT_COLOR_NUM=31 ;;
        *)     PROMPT_COLOR_NUM=35 HOSTTYPE="unknown";;
      esac
      export PS1='\[\033[1;${PROMPT_COLOR_NUM}m\][\u@(${HOSTTYPE})\h \W]$\[\033[00m\] '
      export HISTTIMEFORMAT='%F %T '
      export HISTSIZE=100000
